#!/usr/bin/ruby

require "../lib/fstui.rb"

screen = FSTui::Screen.new

begin
  date_string = Time.now.strftime("%d %^b %Y")
  time_string = Time.now.strftime("%H:%M")
  screen.titlebar.left = date_string
  screen.titlebar.right = time_string
  screen.titlebar.center = "FSTUI DEMO"
  screen.inputbar.prompt = "Enter an item number for more detail : "
  screen.redraw
  
  loop do
    demo_infolist = screen.new_infolist("Infoline: Some info can go here!", 2)
    demo_infolist.left_heading = "LEFT HEADING"
    demo_infolist.right_heading = "RIGHT HEADING"
    (1..25).each do |idx|
      demo_infolist.add_item [["Item #{idx}, Line 1, Left", "Item #{idx}, Line 1, Right"],["Item #{idx}, Line 2, Left", "Item #{idx}, Line 2, Right"]]
    end
    response = demo_infolist.get_response
    demobox = screen.new_messagebox "User selected item #{response} (which is shown to user as item #{response+1})"
    demobox.show
    sleep 2
    demobox.hide
    screen.destroy
    Kernel.exit
  end
ensure
  screen.destroy
end

